version: '3.8'

services:
  backend:
    build: ./automotive-backend
    container_name: automotive_backend
    ports:
      - "8000:8000"
    volumes:
      - ./automotive-backend:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py import_csv_data &&
             python manage.py runserver 0.0.0.0:8000"
    
  frontend:
    build: ./automotive-frontend
    container_name: automotive_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./automotive-frontend:/app
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
