# Generated by Django 5.1.7 on 2025-03-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.IntegerField()),
                ("post_date", models.DateField()),
                ("country_code", models.CharField(max_length=255)),
                (
                    "overall_sentiment",
                    models.CharField(
                        choices=[
                            ("Positive", "Positive"),
                            ("Neutral", "Neutral"),
                            ("Negative", "Negative"),
                        ],
                        max_length=255,
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                (
                    "ownership_status",
                    models.CharField(
                        choices=[
                            ("Owner", "Owner"),
                            ("Pre-Ownership", "Pre-Ownership"),
                            ("Showing Interest", "Showing Interest"),
                        ],
                        max_length=255,
                    ),
                ),
                ("feedback_sentiment", models.CharField(max_length=255)),
                ("feedback_subcategory", models.CharField(max_length=255)),
            ],
        ),
    ]
